Repository rage/tmc-vscode, pull requests merged in 2020-01, with the labels that each got.

#38 Extension storage
  package-lock.json
  package.json
  src/config/storage.ts
  src/test/config/storage.test.ts
Labels: enhancement

#39 Implement oauth
  package-lock.json
  package.json
  resources/style.css
  src/api/tmc.ts
  src/config/storage.ts
  src/extension.ts
  src/init.ts
  src/test/config/storage.test.ts
  src/ui/ui.ts
Labels: login

#47 Add support for requesting organizations, courses and course details
  package-lock.json
  package.json
  src/api/tmc.ts
  tslint.json
Labels: login

#50 Error refactor
  package-lock.json
  package.json
  src/api/tmc.ts
  src/errors.ts
  src/init.ts
Labels: maintenance

#54 Add runtime type checking for TMC API responses
  package-lock.json
  package.json
  src/api/tmc.ts
  src/errors.ts
  tsconfig.json
Labels: maintenance

#55 Treeview visibility rework
  src/init.ts
  src/test/ui/visibility.test.ts
  src/ui/treeview/treeview.ts
  src/ui/treeview/visibility.ts
  src/ui/ui.ts
Labels: maintenance

#69 Add fancy new TMC icon
  media/TMC.svg
  package.json
  src/ui/webview.ts
Labels: enhancement

#63 Download files
  src/api/tmc.ts
  src/api/types.ts
  src/extension.ts
  src/init.ts
  src/utils.ts
Labels: new exercises

#68 Support programmatically triggering callbacks
  src/init.ts
  src/ui/treeview/treeview.ts
Labels: maintenance

#66 Courseview
  resources/style.css
  resources/templates/course.html
  resources/templates/organization.html
  src/api/tmc.ts
  src/api/types.ts
  src/init.ts
Labels: login, maintenance

#73 Refactoring and caching
  resources/styles/bootstrap.min.css
  resources/styles/style.css
  src/api/tmc.ts
  src/config/resources.ts
  src/extension.ts
  src/init.ts
  src/ui/templateEngine.ts
  src/ui/ui.ts
  src/ui/webview.ts
Labels: maintenance
