Repository rage/tmc-vscode, pull requests merged in 2020-02, with the labels that each got.

#78 MVP-level solution for submitting exercises
  package-lock.json
  package.json
  src/api/tmc.ts
  src/api/types.ts
  src/extension.ts
Labels: submitexercise

#80 Fix styling of editor view to match selected theme
  resources/styles/style.css
  resources/templates/course-details.html
Labels: 1h, maintenance

#85 fix bug in exercise selector
  resources/templates/course-details.html
Labels: bug

#87 Add ability to run exercise tests locally
  package.json
  resources/templates/test-result.html
  src/config/resources.ts
  src/extension.ts
  src/init.ts
  src/ui/temporaryWebview.ts
  src/ui/ui.ts
  src/ui/webview.ts
Labels: test-exercise

#99 Workspace rework
  resources/templates/course-details.html
  src/api/exerciseManager.ts
  src/api/tmc.ts
  src/config/resources.ts
  src/config/storage.ts
  src/extension.ts
  src/init.ts
  src/test/config/storage.test.ts
  src/ui/treeview/actions.ts
  src/ui/treeview/handlers.ts
  src/utils.ts
Labels: enhancement

#100 Progress bar
  resources/templates/submission-result.html
  resources/templates/submission-status.html
  resources/templates/test-result.html
  src/extension.ts
  src/ui/templateEngine.ts
Labels: submit exercise, test exercise

#115 Fix bg white on logos
  resources/templates/course.html
  resources/templates/organization.html
Labels: maintenance

#124 Run in background for tests, if passed, submit to server noti
  resources/templates/test-result.html
  src/extension.ts
  src/ui/templateEngine.ts
Labels: test exercise

#120 Submission improvements: notifications & submission feedback
  .vscode/launch.json
  .vscode/tasks.json
  package.json
  resources/styles/bootstrap.min.css
  resources/styles/style.css
  resources/templates/course-details.html
  resources/templates/submission-result.html
  src/api/tmc.ts
  src/api/types.ts
  src/extension.ts
  src/ui/temporaryWebview.ts
Labels: feedback exercise, submit exercise

#126 Refactor visibility groups
  src/init.ts
  src/test/ui/visibility.test.ts
  src/ui/treeview/actions.ts
  src/ui/treeview/handlers.ts
  src/ui/treeview/treeview.ts
  src/ui/treeview/types.ts
  src/ui/treeview/visibility.ts
Labels: maintenance

#128 Compile failed parsing
  resources/styles/style.css
  resources/templates/test-result.html
  src/api/types.ts
  src/extension.ts
  src/ui/templateEngine.ts
  src/utils.ts
Labels: test exercise

#130 Submission compile failed error
  resources/templates/submission-result.html
  src/api/types.ts
  src/ui/templateEngine.ts
Labels: submit exercise

#127 Add command to reset exercises
  package-lock.json
  package.json
  src/api/exerciseManager.ts
  src/extension.ts
Labels: reset exercise

#149 View model solution and notification if submission long in queue
  resources/templates/submission-result.html
  src/extension.ts
  src/ui/templateEngine.ts
Labels: submit exercise

#151 Action refactor
  src/actions/actions.ts
  src/actions/types.ts
  src/extension.ts
  src/init.ts
  src/ui/treeview/actions.ts
  src/ui/treeview/types.ts
  src/utils.ts
Labels: maintenance

#152 Submit to server button, passing tempview panel object
  resources/templates/test-result.html
  src/actions/actions.ts
  src/ui/templateEngine.ts
  src/ui/temporaryWebview.ts
Labels: maintenance, test exercise

#158 Fix langs response type
  src/api/types.ts
Labels: bug

#177 Fix styling errors, center organization images, remove unnecessary text
  resources/styles/style.css
  resources/templates/course.html
  resources/templates/index.html
  resources/templates/organization.html
Labels: maintenance

#179 Remove add new course from navi
  src/init.ts
Labels: maintenance

#181 Fix styling and reset exercise
  resources/templates/running-tests.html
  src/api/tmc.ts
  src/api/workspaceManager.ts
Labels: bug, maintenance
