Repository rage/tmc-vscode, pull requests merged in 2020-03, with the labels that each got.

#184 Status bar
  resources/templates/submission-status.html
  src/actions/actions.ts
  src/extension.ts
  src/ui/ui.ts
Labels: maintenance

#183 Feedback notification
  resources/templates/submission-result.html
Labels: feedback exercise

#192 Add spinners to loading screens
  resources/templates/loading.html
  resources/templates/running-tests.html
Labels: test exercise

#173 Instructions
  CHANGELOG.md
  README.md
  README_old.md
  media/README_click_Explorer.png
  media/README_click_Login.png
  media/README_click_TMC.png
  media/README_getting_started.png
  media/README_submit_test_reset.png
  package.json
  src/extension.ts
Labels: documentation

#216 Separate config for development and production builds
  .vscode/tasks.json
  package-lock.json
  package.json
  src/extension.ts
  src/utils.ts
  tsconfig.production.json
  webpack.common.js
  webpack.dev.js
  webpack.prod.js
Labels: configuration

#208 Course details
  .vscode/settings.json
  package.json
  resources/styles/style.css
  resources/templates/course-details.html
  resources/templates/course.html
  resources/templates/download-exercises.html
  resources/templates/downloading-exercises.html
  resources/templates/login.html
  resources/templates/organization.html
  resources/templates/submission-result.html
  src/actions/actions.ts
  src/api/tmc.ts
  src/api/types.ts
  src/api/workspaceManager.ts
  src/config/userdata.ts
  src/extension.ts
  src/init.ts
  src/test/config/storage.test.ts
  src/ui/templateEngine.ts
  src/ui/treeview/handlers.ts
  src/ui/treeview/treeview.ts
  src/ui/treeview/types.ts
  src/ui/treeview/visibility.ts
  src/ui/webview.ts
  src/utils.ts
Labels: course details

#230 Remove button for courses
  resources/templates/index.html
  src/actions/actions.ts
  src/init.ts
Labels: course details

#229 Remove unecessary console logs and add error handling for actions.ts
  package-lock.json
  package.json
  resources/templates/course.html
  src/actions/index.ts
  src/actions/user.ts
  src/actions/webview.ts
  src/actions/workspace.ts
  src/api/workspaceManager.ts
  src/extension.ts
  src/init.ts
  src/ui/templateEngine.ts
  src/utils.ts
Labels: maintenance

#239 Implement persistent data validator & updater
  src/api/tmc.ts
  src/config/storage.ts
  src/config/validate.ts
  src/extension.ts
  src/init.ts
  src/test/config/storage.test.ts
  src/ui/treeview/types.ts
Labels: maintenance
